
service: march-madness-calcutta-cognito

package:
  individually: true

plugins:
  - serverless-bundle

custom:
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: nodejs16.x
  timeout: 15
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - cognito-idp:AdminGetUser
        - cognito-idp:AdminInitiateAuth
      Resource: arn:aws:cognito-idp:us-east-1:329156245350:userpool/us-east-1_uOQeKJ4OE
    - Effect: Allow
      Action: sts:AssumeRole
      Resource: arn:aws:iam::329156245350:role/lambda-migrate-user
  environment:
    DB_NAME: ${env:DB_NAME}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    ASSUMED_ROLE_ARN: arn:aws:iam::${env:AWS_PEER_ACCOUNT_ID}:role/calcutta-${self:custom.stage}-assumed-role
    OLD_USER_POOL_ID: ${env:OLD_USER_POOL_ID}
    OLD_COGNITO_CLIENT_ID: ${env:OLD_COGNITO_CLIENT_ID}

functions:
  addUserAfterSignup:
    handler: auth/signup.addUserAfterSignup
    events:
      - cognitoUserPool:
          pool: CalcuttaPool
          trigger: PostConfirmation
    vpc:
      securityGroupIds:
        - Ref: LambdaSG
      subnetIds:
        - Ref: LambdaSubnet1
        - Ref: LambdaSubnet2
        - Ref: LambdaSubnet3

  syncUserInDatabase:
    handler: auth/postAuth.syncUserInDatabase
    events:
      - cognitoUserPool:
          pool: CalcuttaPool
          trigger: PostAuthentication
    vpc:
      securityGroupIds:
        - Ref: LambdaSG
      subnetIds:
        - Ref: LambdaSubnet1
        - Ref: LambdaSubnet2
        - Ref: LambdaSubnet3

  migrateUser:
    handler: auth/migration.migrateUser
    events:
      - cognitoUserPool:
          pool: CalcuttaPool
          trigger: UserMigration

  preAuthTrigger:
    handler: auth/preAuth.preAuthTrigger
    events:
      - cognitoUserPool:
          pool: CalcuttaPool
          trigger: PreAuthentication
  
resources:
  - ${file(resources/cognito.yml)}
  - ${file(resources/vpc.yml)}
  - ${file(resources/subnets.yml)}
  - ${file(resources/security-groups.yml)}
  - ${file(resources/route-tables.yml)}
  - ${file(resources/subnet-route-table-associations.yml)}
  - ${file(resources/internet-gateway.yml)}
  - ${file(resources/routes.yml)}
  - ${file(resources/roles.yml)}