Resources:
  CalcuttaVPCPeerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: calcutta-${self:custom.stage}-peer-role
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              AWS: ${env.AWS_PEER_ACCOUNT_ID}
            Action: 
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: ec2:AcceptVpcPeeringConnection
                Resource: '*'