Resources:
  LambdaRoute:
    Type: AWS::EC2::Route
    DependsOn: 
      - CalcuttaInternetGateway
      - CalcuttaGatewayAttachment
    Properties:
      RouteTableId:
        Ref: LambdaRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: CalcuttaInternetGateway