Resources:
  LambdaSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'Lambda outbound'
      GroupName: LambdaDMZ
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      VpcId:
        Ref: CalcuttaCognitoVPC